src/index.js
src/index.test.js

Single quotes in string literals don't get escaped when handling a value. This escapes them properly.

Escape single quotes in string literals

---

src/index.js
src/index.test.js

This fixes #13, but an in operator whit an implied and will result in double paranthesis
```
[{
SomeProp: {
in: [1, 2, 3]
}
},
{
AnotherProp: 4
}];
```
```
?$filter=((SomeProp eq 1 or SomeProp eq 2 or SomeProp eq 3)) and (AnotherProp eq 4)
```

Add parenthesis around 'in' operator

---

README.md
src/index.js
src/index.test.js

I've added a convention, passing the value in the form of `{ cast: 'type', value: 'actualValue' }`, you can specify its custom type.
Added support for GUID.
More types can easily be added like this.

Data Types: add GUID support

---

src/index.js
src/index.test.js

Supports format on the query.
```
const format = 'json';
buildQuery({ format });
// ?$format=json
```

Support formats

---

src/index.js
src/index.test.js

'not' can be specified as an as the key for an array or an object to prepend 'not' to a filter:
e.g. `filter:{not: {SomeProp:{'startswith': 'bar'}}}` generates `?$filter=not startswith(SomeProp,'foo')`

Add basic support for 'not' logical operator

---

package.json
tsconfig.cjs.json
tsconfig.dts.json
tsconfig.esm.json
tsconfig.json

Earlier only esm modules were generated, which does not work with projects with commonjs module system. Therefore, this PR adds support for generating commonjs module.
Details: 
- Added 3 new tsconfig files that inherits from the base.
- Changed the build script so that is supports generating commonjs
module along with esm.
- Also corrected the main and module entries in package.json
@techniq Can you review the changes?

Adding commonjs module support

---

package.json

Addresses #52 
Moves [tslib](https://www.npmjs.com/package/tslib) to a dependency so a non typescript project does not need to manually install it along with this package.

changed tslib from a dev dependency to a dependency

---

README.md
src/index.ts
test/index.test.ts

Instead of exploding `{ SomeProp: { in: [1, 2, 3] } }` to `(SomeProp eq 1 or SomeProp eq 2 or SomeProp eq 3)`, it is converted to odata in opertor: `SomeProp in (1,2,3)`.
The negated case (`not in`) like `{ not: { SomeProp: { in: [1, 2, 3] } } }` is translated to `not(SomeProp in (1,2,3))`.
Closes #22

refactor: preliminary support for 'in' operator

---

src/index.ts
test/index.test.ts

Resolves #66
- Allow zero in query values (now $top=0 and $skip=0 works)
- Add some tests

[FIX] Allow zero in query values

---

src/index.ts
test/index.test.ts

The OData specification supports querying simple collections using the any/all operators. 
One such example can be seen [here](https://docs.microsoft.com/en-us/azure/search/search-query-odata-collection-operators#examples).
I found that it was not possible to generate such a filter using odata-query. This PR is an attempt to remedy the string collection case in particular. Similar queries should also be allowed against simple numeric collections. If you'd like me to work out a PR for that case, I may have time to.
Please let me know what revisions would be necessary.
Thank you for your hard work on odata-query.

Added support for any and all queries on simple string collections.

---

src/index.ts
test/index.test.ts

```js
const filter = {
tags: {
any: {
'tags': {
'in': [TAG1', 'TAG2']
}
}
}
}
buildQuery({ filter }) => "tags/any(tags:tags/tags in ('TAG1', 'TAG2'))"; 
``` 
```js
buildQuery({ filter }) => "tags/any(tags:tags in ('TAG1', 'TAG2'))"; 
``` 
To omit extra `/tags` in query, special const `ITEM_ROOT` was added.
What do you think about the idea?

Add ability to use all filters on the item itself with collection operators (any / all)

---

README.md
src/index.ts
test/index.test.ts

Addition to PR [#72 ](https://github.com/techniq/odata-query/pull/72)
- fix for 'and' operator
- updates in README with examples for ability to use all filters on the item itself with collection operators (any / all)

Support for collections without nested property key (fix for 'and' operator, updates in README)

---

src/index.ts
test/index.test.ts

A refactoring of the aliases to allow aliases on filters, functions, and key.
Aliases are values ​​that are collected during the querystring generation process.
Applying conditions based on the difference between undefined and null.
Null is a permitted value in OData queries, while undefined is removed from it.

Has Operator, Aliases Refactoring and Undefined vs Null

---

README.md
src/index.ts
test/index.test.ts

According to oData documentation decimal number should be represented as `[0-9]+.[0-9]+M|m`

Added support of decimal numbers

---

src/index.ts

This change ignores more `undefined` filter values, which helps building dynamic odata queries with optional filters.
Specifically two new cases are handled, which previously would generate bad odata query (1) or crash (2):
```js
const filter = {
a: undefined,  // was always ignored
b: {
ge: undefined,  // (1) new: ignore nested object keys such as operators eq/ge/gt/le/lt
},
or: undefined,  // (2) new: ignore keywords such as logical and/or/not
}
```

Enh: Ignore more undefined filters

---

src/index.ts
test/index.test.ts

This filter:
```js
{ 
a: 1, 
or: { b: 2, c: 3 },
}
```
was incorrectly converted to: `a eq 1 and b eq 2 or c eq 3`.
Brackets are required to fix the precedence of `or` as expressed in the object structure.
After this fix:
`a eq 1 and (b eq 2 or c eq 3)`

Fix: bad operator precedence inside object

---

src/index.ts
test/index.test.ts

Add $skip support to Expand options
Fix #107

Issue #107 - Add $skip support to Expand options

---

src/index.ts
test/index.test.ts
test/test-interface.ts

This changeset manages #95 and enhances the Filter type in order to build filter objects as `TypedFilter<T>` or `Array<string | PlainObject | TypedFilter<T>>`. In this way it would be possible to have type safety for the property name. 
Please note that: 
- the type of each and every key in the TypedFilter is `any` in order to support oData operator passed as a plain object. 
- the changes do not support property name type safety for nested properties

Handle Typed Property Name in Filter - Issue #95

---

src/index.ts
test/index.test.ts

According to Oasis ABNF for OData, not operator must be followed by RWS, a.k.a. a required whitespace.
The library puts no space between not and the following brackets ().
This PR is to fix this issue.

fix: added SPACE after NOT

---

package.json

When specifying the `odata-query` package source as github, this allows the source to be built as part of the npm install steps.

chore: build package as part of npm prepare step

---

README.md
src/index.ts

Adds support for the [`matchesPattern`](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_matchesPattern) boolean odata function.

feat: support matchesPattern boolean function

---

src/index.ts
test/index.test.ts

@techniq This fixes the problem you called out in your `TODO` comments within the tests where conditions were being duplicated.  The duplicated are no longer included when building the query, and I've restored the skipped tests.

fix: prevent duplicated conditions & restore skipped tests

---

package.json

it seems possible that on CI the backgrounded  command is not finishing and that's why the d.ts files are not included in the release? Ether way, it doesn't seem necessary to background the task

build: run tsc and vite build sequentially
